/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockStrategyInterface extends Interface {
    getFunction(nameOrSignature: "asset" | "deploy" | "fxrpToken" | "isActive" | "name" | "overDeliveryAmount" | "report" | "reset" | "setOverDeliveryAmount" | "setShouldFailDeploy" | "setShouldFailWithdraw" | "setYieldAmount" | "shouldFailDeploy" | "shouldFailWithdraw" | "strategyName" | "totalAssets" | "totalDeployed" | "withdraw" | "yieldAmount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DeployedToStrategy" | "StrategyReport" | "WithdrawnFromStrategy"): EventFragment;

    encodeFunctionData(functionFragment: 'asset', values?: undefined): string;
encodeFunctionData(functionFragment: 'deploy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fxrpToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'isActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'overDeliveryAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'report', values?: undefined): string;
encodeFunctionData(functionFragment: 'reset', values?: undefined): string;
encodeFunctionData(functionFragment: 'setOverDeliveryAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setShouldFailDeploy', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setShouldFailWithdraw', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setYieldAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'shouldFailDeploy', values?: undefined): string;
encodeFunctionData(functionFragment: 'shouldFailWithdraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'strategyName', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalDeployed', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'yieldAmount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'asset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deploy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fxrpToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'overDeliveryAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'report', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOverDeliveryAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setShouldFailDeploy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setShouldFailWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setYieldAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shouldFailDeploy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shouldFailWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'strategyName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDeployed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yieldAmount', data: BytesLike): Result;
  }

  
    export namespace DeployedToStrategyEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyReportEvent {
      export type InputTuple = [profit: BigNumberish, loss: BigNumberish, totalAssets: BigNumberish];
      export type OutputTuple = [profit: bigint, loss: bigint, totalAssets: bigint];
      export interface OutputObject {profit: bigint, loss: bigint, totalAssets: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnFromStrategyEvent {
      export type InputTuple = [amount: BigNumberish, actualAmount: BigNumberish];
      export type OutputTuple = [amount: bigint, actualAmount: bigint];
      export interface OutputObject {amount: bigint, actualAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockStrategy extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockStrategy;
    waitForDeployment(): Promise<this>;

    interface: MockStrategyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    asset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    deploy: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fxrpToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    overDeliveryAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    report: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {profit: bigint, loss: bigint, assets: bigint }],
      'nonpayable'
    >
    

    
    reset: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setOverDeliveryAmount: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setShouldFailDeploy: TypedContractMethod<
      [_fail: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setShouldFailWithdraw: TypedContractMethod<
      [_fail: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setYieldAmount: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    shouldFailDeploy: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    shouldFailWithdraw: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    strategyName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalDeployed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [amount: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    yieldAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'asset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deploy'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fxrpToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'overDeliveryAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'report'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {profit: bigint, loss: bigint, assets: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reset'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOverDeliveryAmount'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setShouldFailDeploy'): TypedContractMethod<
      [_fail: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setShouldFailWithdraw'): TypedContractMethod<
      [_fail: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setYieldAmount'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shouldFailDeploy'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'shouldFailWithdraw'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'strategyName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalDeployed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [amount: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'yieldAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'DeployedToStrategy'): TypedContractEvent<DeployedToStrategyEvent.InputTuple, DeployedToStrategyEvent.OutputTuple, DeployedToStrategyEvent.OutputObject>;
getEvent(key: 'StrategyReport'): TypedContractEvent<StrategyReportEvent.InputTuple, StrategyReportEvent.OutputTuple, StrategyReportEvent.OutputObject>;
getEvent(key: 'WithdrawnFromStrategy'): TypedContractEvent<WithdrawnFromStrategyEvent.InputTuple, WithdrawnFromStrategyEvent.OutputTuple, WithdrawnFromStrategyEvent.OutputObject>;

    filters: {
      
      'DeployedToStrategy(uint256)': TypedContractEvent<DeployedToStrategyEvent.InputTuple, DeployedToStrategyEvent.OutputTuple, DeployedToStrategyEvent.OutputObject>;
      DeployedToStrategy: TypedContractEvent<DeployedToStrategyEvent.InputTuple, DeployedToStrategyEvent.OutputTuple, DeployedToStrategyEvent.OutputObject>;
    

      'StrategyReport(uint256,uint256,uint256)': TypedContractEvent<StrategyReportEvent.InputTuple, StrategyReportEvent.OutputTuple, StrategyReportEvent.OutputObject>;
      StrategyReport: TypedContractEvent<StrategyReportEvent.InputTuple, StrategyReportEvent.OutputTuple, StrategyReportEvent.OutputObject>;
    

      'WithdrawnFromStrategy(uint256,uint256)': TypedContractEvent<WithdrawnFromStrategyEvent.InputTuple, WithdrawnFromStrategyEvent.OutputTuple, WithdrawnFromStrategyEvent.OutputObject>;
      WithdrawnFromStrategy: TypedContractEvent<WithdrawnFromStrategyEvent.InputTuple, WithdrawnFromStrategyEvent.OutputTuple, WithdrawnFromStrategyEvent.OutputObject>;
    
    };
  }