/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace VaultController {
      
    export type BridgeRequestStruct = {user: AddressLike, vault: AddressLike, xrpAmount: BigNumberish, fxrpExpected: BigNumberish, timestamp: BigNumberish, status: BigNumberish, xrplTxHash: string, flareTxHash: string}

    export type BridgeRequestStructOutput = [user: string, vault: string, xrpAmount: bigint, fxrpExpected: bigint, timestamp: bigint, status: bigint, xrplTxHash: string, flareTxHash: string] & {user: string, vault: string, xrpAmount: bigint, fxrpExpected: bigint, timestamp: bigint, status: bigint, xrplTxHash: string, flareTxHash: string }
  
    }

  export interface VaultControllerInterface extends Interface {
    getFunction(nameOrSignature: "COMPOUNDER_ROLE" | "DEFAULT_ADMIN_ROLE" | "OPERATOR_ROLE" | "addCompounder" | "addOperator" | "bridgeRequests" | "createBridgeRequest" | "deregisterVault" | "executeCompound" | "getBridgeRequest" | "getRoleAdmin" | "getVaultCount" | "grantRole" | "hasRole" | "lastCompoundTime" | "minCompoundInterval" | "registerVault" | "registeredVaults" | "removeCompounder" | "removeOperator" | "renounceRole" | "revokeRole" | "setMinCompoundInterval" | "supportsInterface" | "updateBridgeStatus" | "vaultList"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BridgeRequestCreated" | "BridgeStatusUpdated" | "CompoundExecuted" | "OperatorAdded" | "OperatorRemoved" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "VaultDeregistered" | "VaultRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'COMPOUNDER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'addCompounder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addOperator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'bridgeRequests', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'createBridgeRequest', values: [AddressLike, AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'deregisterVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'executeCompound', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getBridgeRequest', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getVaultCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'lastCompoundTime', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'minCompoundInterval', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registeredVaults', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeCompounder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeOperator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setMinCompoundInterval', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateBridgeStatus', values: [BytesLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'vaultList', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'COMPOUNDER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addCompounder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bridgeRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createBridgeRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deregisterVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeCompound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBridgeRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVaultCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastCompoundTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minCompoundInterval', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registeredVaults', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeCompounder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinCompoundInterval', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateBridgeStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vaultList', data: BytesLike): Result;
  }

  
    export namespace BridgeRequestCreatedEvent {
      export type InputTuple = [requestId: BytesLike, user: AddressLike, xrpAmount: BigNumberish];
      export type OutputTuple = [requestId: string, user: string, xrpAmount: bigint];
      export interface OutputObject {requestId: string, user: string, xrpAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BridgeStatusUpdatedEvent {
      export type InputTuple = [requestId: BytesLike, newStatus: BigNumberish];
      export type OutputTuple = [requestId: string, newStatus: bigint];
      export interface OutputObject {requestId: string, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CompoundExecutedEvent {
      export type InputTuple = [vault: AddressLike, yieldAmount: BigNumberish];
      export type OutputTuple = [vault: string, yieldAmount: bigint];
      export interface OutputObject {vault: string, yieldAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OperatorAddedEvent {
      export type InputTuple = [operator: AddressLike];
      export type OutputTuple = [operator: string];
      export interface OutputObject {operator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OperatorRemovedEvent {
      export type InputTuple = [operator: AddressLike];
      export type OutputTuple = [operator: string];
      export interface OutputObject {operator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultDeregisteredEvent {
      export type InputTuple = [vault: AddressLike];
      export type OutputTuple = [vault: string];
      export interface OutputObject {vault: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultRegisteredEvent {
      export type InputTuple = [vault: AddressLike];
      export type OutputTuple = [vault: string];
      export interface OutputObject {vault: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VaultController extends BaseContract {
    
    connect(runner?: ContractRunner | null): VaultController;
    waitForDeployment(): Promise<this>;

    interface: VaultControllerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COMPOUNDER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    OPERATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addCompounder: TypedContractMethod<
      [compounder: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addOperator: TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    bridgeRequests: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint, string, string] & {user: string, vault: string, xrpAmount: bigint, fxrpExpected: bigint, timestamp: bigint, status: bigint, xrplTxHash: string, flareTxHash: string }],
      'view'
    >
    

    
    createBridgeRequest: TypedContractMethod<
      [user: AddressLike, vault: AddressLike, xrpAmount: BigNumberish, xrplTxHash: string, ],
      [string],
      'nonpayable'
    >
    

    
    deregisterVault: TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    executeCompound: TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getBridgeRequest: TypedContractMethod<
      [requestId: BytesLike, ],
      [VaultController.BridgeRequestStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getVaultCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    lastCompoundTime: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    minCompoundInterval: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerVault: TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registeredVaults: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    removeCompounder: TypedContractMethod<
      [compounder: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeOperator: TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMinCompoundInterval: TypedContractMethod<
      [interval: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    updateBridgeStatus: TypedContractMethod<
      [requestId: BytesLike, newStatus: BigNumberish, flareTxHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    vaultList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COMPOUNDER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'OPERATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addCompounder'): TypedContractMethod<
      [compounder: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addOperator'): TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'bridgeRequests'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint, string, string] & {user: string, vault: string, xrpAmount: bigint, fxrpExpected: bigint, timestamp: bigint, status: bigint, xrplTxHash: string, flareTxHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'createBridgeRequest'): TypedContractMethod<
      [user: AddressLike, vault: AddressLike, xrpAmount: BigNumberish, xrplTxHash: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deregisterVault'): TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeCompound'): TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBridgeRequest'): TypedContractMethod<
      [requestId: BytesLike, ],
      [VaultController.BridgeRequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getVaultCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastCompoundTime'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minCompoundInterval'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerVault'): TypedContractMethod<
      [vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registeredVaults'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'removeCompounder'): TypedContractMethod<
      [compounder: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeOperator'): TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinCompoundInterval'): TypedContractMethod<
      [interval: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'updateBridgeStatus'): TypedContractMethod<
      [requestId: BytesLike, newStatus: BigNumberish, flareTxHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vaultList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'BridgeRequestCreated'): TypedContractEvent<BridgeRequestCreatedEvent.InputTuple, BridgeRequestCreatedEvent.OutputTuple, BridgeRequestCreatedEvent.OutputObject>;
getEvent(key: 'BridgeStatusUpdated'): TypedContractEvent<BridgeStatusUpdatedEvent.InputTuple, BridgeStatusUpdatedEvent.OutputTuple, BridgeStatusUpdatedEvent.OutputObject>;
getEvent(key: 'CompoundExecuted'): TypedContractEvent<CompoundExecutedEvent.InputTuple, CompoundExecutedEvent.OutputTuple, CompoundExecutedEvent.OutputObject>;
getEvent(key: 'OperatorAdded'): TypedContractEvent<OperatorAddedEvent.InputTuple, OperatorAddedEvent.OutputTuple, OperatorAddedEvent.OutputObject>;
getEvent(key: 'OperatorRemoved'): TypedContractEvent<OperatorRemovedEvent.InputTuple, OperatorRemovedEvent.OutputTuple, OperatorRemovedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'VaultDeregistered'): TypedContractEvent<VaultDeregisteredEvent.InputTuple, VaultDeregisteredEvent.OutputTuple, VaultDeregisteredEvent.OutputObject>;
getEvent(key: 'VaultRegistered'): TypedContractEvent<VaultRegisteredEvent.InputTuple, VaultRegisteredEvent.OutputTuple, VaultRegisteredEvent.OutputObject>;

    filters: {
      
      'BridgeRequestCreated(bytes32,address,uint256)': TypedContractEvent<BridgeRequestCreatedEvent.InputTuple, BridgeRequestCreatedEvent.OutputTuple, BridgeRequestCreatedEvent.OutputObject>;
      BridgeRequestCreated: TypedContractEvent<BridgeRequestCreatedEvent.InputTuple, BridgeRequestCreatedEvent.OutputTuple, BridgeRequestCreatedEvent.OutputObject>;
    

      'BridgeStatusUpdated(bytes32,uint8)': TypedContractEvent<BridgeStatusUpdatedEvent.InputTuple, BridgeStatusUpdatedEvent.OutputTuple, BridgeStatusUpdatedEvent.OutputObject>;
      BridgeStatusUpdated: TypedContractEvent<BridgeStatusUpdatedEvent.InputTuple, BridgeStatusUpdatedEvent.OutputTuple, BridgeStatusUpdatedEvent.OutputObject>;
    

      'CompoundExecuted(address,uint256)': TypedContractEvent<CompoundExecutedEvent.InputTuple, CompoundExecutedEvent.OutputTuple, CompoundExecutedEvent.OutputObject>;
      CompoundExecuted: TypedContractEvent<CompoundExecutedEvent.InputTuple, CompoundExecutedEvent.OutputTuple, CompoundExecutedEvent.OutputObject>;
    

      'OperatorAdded(address)': TypedContractEvent<OperatorAddedEvent.InputTuple, OperatorAddedEvent.OutputTuple, OperatorAddedEvent.OutputObject>;
      OperatorAdded: TypedContractEvent<OperatorAddedEvent.InputTuple, OperatorAddedEvent.OutputTuple, OperatorAddedEvent.OutputObject>;
    

      'OperatorRemoved(address)': TypedContractEvent<OperatorRemovedEvent.InputTuple, OperatorRemovedEvent.OutputTuple, OperatorRemovedEvent.OutputObject>;
      OperatorRemoved: TypedContractEvent<OperatorRemovedEvent.InputTuple, OperatorRemovedEvent.OutputTuple, OperatorRemovedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'VaultDeregistered(address)': TypedContractEvent<VaultDeregisteredEvent.InputTuple, VaultDeregisteredEvent.OutputTuple, VaultDeregisteredEvent.OutputObject>;
      VaultDeregistered: TypedContractEvent<VaultDeregisteredEvent.InputTuple, VaultDeregisteredEvent.OutputTuple, VaultDeregisteredEvent.OutputObject>;
    

      'VaultRegistered(address)': TypedContractEvent<VaultRegisteredEvent.InputTuple, VaultRegisteredEvent.OutputTuple, VaultRegisteredEvent.OutputObject>;
      VaultRegistered: TypedContractEvent<VaultRegisteredEvent.InputTuple, VaultRegisteredEvent.OutputTuple, VaultRegisteredEvent.OutputObject>;
    
    };
  }