/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ShXRPVault {
      
    export type StrategyInfoStruct = {strategyAddress: AddressLike, targetBps: BigNumberish, status: BigNumberish, totalDeployed: BigNumberish, lastReportTimestamp: BigNumberish}

    export type StrategyInfoStructOutput = [strategyAddress: string, targetBps: bigint, status: bigint, totalDeployed: bigint, lastReportTimestamp: bigint] & {strategyAddress: string, targetBps: bigint, status: bigint, totalDeployed: bigint, lastReportTimestamp: bigint }
  
    }

  export interface ShXRPVaultInterface extends Interface {
    getFunction(nameOrSignature: "DEPOSIT_FEE_BPS" | "WITHDRAW_FEE_BPS" | "activateStrategy" | "addOperator" | "addStrategy" | "allowance" | "approve" | "asset" | "balanceOf" | "bufferTargetBps" | "convertToAssets" | "convertToShares" | "decimals" | "deployToStrategy" | "deposit" | "depositLimit" | "getActiveStrategies" | "getAllStrategies" | "getBufferBalance" | "getBufferStatus" | "getBufferTarget" | "getCurrentAllocations" | "getStrategyInfo" | "getTotalDeployed" | "maxDeposit" | "maxMint" | "maxRedeem" | "maxWithdraw" | "minDeposit" | "mint" | "name" | "operators" | "owner" | "pause" | "pauseStrategy" | "paused" | "previewDeposit" | "previewMint" | "previewRedeem" | "previewRedeemWithBoost" | "previewWithdraw" | "redeem" | "removeOperator" | "removeStrategy" | "renounceOwnership" | "reportStrategy" | "resumeStrategy" | "revenueRouter" | "setBufferTarget" | "setDepositLimit" | "setMinDeposit" | "stakingBoost" | "strategies" | "strategyList" | "symbol" | "totalAssets" | "totalStrategyTargetBps" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership" | "unpause" | "updateAllocation" | "withdraw" | "withdrawFromStrategy"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "BufferTargetUpdated" | "DeployedToStrategy" | "Deposit" | "DepositLimitUpdated" | "FeeTransferred" | "MinDepositUpdated" | "OperatorAdded" | "OperatorRemoved" | "OwnershipTransferred" | "Paused" | "StrategyAdded" | "StrategyAllocationUpdated" | "StrategyRemoved" | "StrategyReported" | "StrategyStatusUpdated" | "Transfer" | "Unpaused" | "Withdraw" | "WithdrawnFromStrategy"): EventFragment;

    encodeFunctionData(functionFragment: 'DEPOSIT_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'WITHDRAW_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'activateStrategy', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addOperator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addStrategy', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'asset', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'bufferTargetBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'convertToAssets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'convertToShares', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'deployToStrategy', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'depositLimit', values?: undefined): string;
encodeFunctionData(functionFragment: 'getActiveStrategies', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllStrategies', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBufferBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBufferStatus', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBufferTarget', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCurrentAllocations', values?: undefined): string;
encodeFunctionData(functionFragment: 'getStrategyInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTotalDeployed', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxDeposit', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxMint', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxRedeem', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxWithdraw', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'minDeposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'mint', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'operators', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseStrategy', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'previewDeposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewMint', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewRedeem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewRedeemWithBoost', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'previewWithdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'redeem', values: [BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'removeOperator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeStrategy', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reportStrategy', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'resumeStrategy', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revenueRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'setBufferTarget', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDepositLimit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMinDeposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakingBoost', values?: undefined): string;
encodeFunctionData(functionFragment: 'strategies', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'strategyList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalStrategyTargetBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateAllocation', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawFromStrategy', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEPOSIT_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WITHDRAW_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activateStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'asset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bufferTargetBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'convertToAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'convertToShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployToStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveStrategies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllStrategies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBufferBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBufferStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBufferTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentAllocations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStrategyInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalDeployed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxRedeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewRedeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewRedeemWithBoost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reportStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resumeStrategy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revenueRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBufferTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDepositLimit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingBoost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'strategies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'strategyList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalStrategyTargetBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateAllocation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFromStrategy', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BufferTargetUpdatedEvent {
      export type InputTuple = [newTargetBps: BigNumberish];
      export type OutputTuple = [newTargetBps: bigint];
      export interface OutputObject {newTargetBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DeployedToStrategyEvent {
      export type InputTuple = [strategy: AddressLike, amount: BigNumberish];
      export type OutputTuple = [strategy: string, amount: bigint];
      export interface OutputObject {strategy: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [sender: AddressLike, owner: AddressLike, assets: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [sender: string, owner: string, assets: bigint, shares: bigint];
      export interface OutputObject {sender: string, owner: string, assets: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositLimitUpdatedEvent {
      export type InputTuple = [newDepositLimit: BigNumberish];
      export type OutputTuple = [newDepositLimit: bigint];
      export interface OutputObject {newDepositLimit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeTransferredEvent {
      export type InputTuple = [feeType: string, amount: BigNumberish, recipient: AddressLike];
      export type OutputTuple = [feeType: string, amount: bigint, recipient: string];
      export interface OutputObject {feeType: string, amount: bigint, recipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinDepositUpdatedEvent {
      export type InputTuple = [newMinDeposit: BigNumberish];
      export type OutputTuple = [newMinDeposit: bigint];
      export interface OutputObject {newMinDeposit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OperatorAddedEvent {
      export type InputTuple = [operator: AddressLike];
      export type OutputTuple = [operator: string];
      export interface OutputObject {operator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OperatorRemovedEvent {
      export type InputTuple = [operator: AddressLike];
      export type OutputTuple = [operator: string];
      export interface OutputObject {operator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyAddedEvent {
      export type InputTuple = [strategy: AddressLike, targetBps: BigNumberish];
      export type OutputTuple = [strategy: string, targetBps: bigint];
      export interface OutputObject {strategy: string, targetBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyAllocationUpdatedEvent {
      export type InputTuple = [strategy: AddressLike, newTargetBps: BigNumberish];
      export type OutputTuple = [strategy: string, newTargetBps: bigint];
      export interface OutputObject {strategy: string, newTargetBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyRemovedEvent {
      export type InputTuple = [strategy: AddressLike];
      export type OutputTuple = [strategy: string];
      export interface OutputObject {strategy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyReportedEvent {
      export type InputTuple = [strategy: AddressLike, profit: BigNumberish, loss: BigNumberish, totalAssets: BigNumberish];
      export type OutputTuple = [strategy: string, profit: bigint, loss: bigint, totalAssets: bigint];
      export interface OutputObject {strategy: string, profit: bigint, loss: bigint, totalAssets: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyStatusUpdatedEvent {
      export type InputTuple = [strategy: AddressLike, newStatus: BigNumberish];
      export type OutputTuple = [strategy: string, newStatus: bigint];
      export interface OutputObject {strategy: string, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [sender: AddressLike, receiver: AddressLike, owner: AddressLike, assets: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, owner: string, assets: bigint, shares: bigint];
      export interface OutputObject {sender: string, receiver: string, owner: string, assets: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnFromStrategyEvent {
      export type InputTuple = [strategy: AddressLike, amount: BigNumberish, actualAmount: BigNumberish];
      export type OutputTuple = [strategy: string, amount: bigint, actualAmount: bigint];
      export interface OutputObject {strategy: string, amount: bigint, actualAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ShXRPVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): ShXRPVault;
    waitForDeployment(): Promise<this>;

    interface: ShXRPVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEPOSIT_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WITHDRAW_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    activateStrategy: TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addOperator: TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addStrategy: TypedContractMethod<
      [strategy: AddressLike, targetBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    asset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    bufferTargetBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    convertToAssets: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    convertToShares: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deployToStrategy: TypedContractMethod<
      [strategy: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    depositLimit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getActiveStrategies: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getAllStrategies: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getBufferBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getBufferStatus: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint] & {current: bigint, target: bigint, deficit: bigint, surplus: bigint, targetBps: bigint }],
      'view'
    >
    

    
    getBufferTarget: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCurrentAllocations: TypedContractMethod<
      [],
      [[string[], bigint[], bigint[]] & {strategies_: string[], allocations: bigint[], targets: bigint[] }],
      'view'
    >
    

    
    getStrategyInfo: TypedContractMethod<
      [strategy: AddressLike, ],
      [ShXRPVault.StrategyInfoStructOutput],
      'view'
    >
    

    
    getTotalDeployed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxDeposit: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maxMint: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maxRedeem: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    maxWithdraw: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    minDeposit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    operators: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    pauseStrategy: TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    previewDeposit: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    previewMint: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    previewRedeem: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    previewRedeemWithBoost: TypedContractMethod<
      [shares: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    previewWithdraw: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, owner: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    removeOperator: TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeStrategy: TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reportStrategy: TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    resumeStrategy: TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revenueRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setBufferTarget: TypedContractMethod<
      [newTargetBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setDepositLimit: TypedContractMethod<
      [newDepositLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMinDeposit: TypedContractMethod<
      [newMinDeposit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakingBoost: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    strategies: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint] & {strategyAddress: string, targetBps: bigint, status: bigint, totalDeployed: bigint, lastReportTimestamp: bigint }],
      'view'
    >
    

    
    strategyList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalStrategyTargetBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateAllocation: TypedContractMethod<
      [strategy: AddressLike, newTargetBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, owner: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    withdrawFromStrategy: TypedContractMethod<
      [strategy: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEPOSIT_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WITHDRAW_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activateStrategy'): TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addOperator'): TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addStrategy'): TypedContractMethod<
      [strategy: AddressLike, targetBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'asset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bufferTargetBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'convertToAssets'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'convertToShares'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deployToStrategy'): TypedContractMethod<
      [strategy: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositLimit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getActiveStrategies'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllStrategies'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getBufferBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBufferStatus'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint] & {current: bigint, target: bigint, deficit: bigint, surplus: bigint, targetBps: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getBufferTarget'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCurrentAllocations'): TypedContractMethod<
      [],
      [[string[], bigint[], bigint[]] & {strategies_: string[], allocations: bigint[], targets: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getStrategyInfo'): TypedContractMethod<
      [strategy: AddressLike, ],
      [ShXRPVault.StrategyInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalDeployed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxDeposit'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxMint'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxRedeem'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxWithdraw'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minDeposit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'operators'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pauseStrategy'): TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'previewDeposit'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewMint'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewRedeem'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewRedeemWithBoost'): TypedContractMethod<
      [shares: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewWithdraw'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [shares: BigNumberish, receiver: AddressLike, owner: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeOperator'): TypedContractMethod<
      [operator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeStrategy'): TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reportStrategy'): TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resumeStrategy'): TypedContractMethod<
      [strategy: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revenueRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setBufferTarget'): TypedContractMethod<
      [newTargetBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDepositLimit'): TypedContractMethod<
      [newDepositLimit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinDeposit'): TypedContractMethod<
      [newMinDeposit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakingBoost'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'strategies'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint] & {strategyAddress: string, targetBps: bigint, status: bigint, totalDeployed: bigint, lastReportTimestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'strategyList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalStrategyTargetBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateAllocation'): TypedContractMethod<
      [strategy: AddressLike, newTargetBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [assets: BigNumberish, receiver: AddressLike, owner: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFromStrategy'): TypedContractMethod<
      [strategy: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'BufferTargetUpdated'): TypedContractEvent<BufferTargetUpdatedEvent.InputTuple, BufferTargetUpdatedEvent.OutputTuple, BufferTargetUpdatedEvent.OutputObject>;
getEvent(key: 'DeployedToStrategy'): TypedContractEvent<DeployedToStrategyEvent.InputTuple, DeployedToStrategyEvent.OutputTuple, DeployedToStrategyEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'DepositLimitUpdated'): TypedContractEvent<DepositLimitUpdatedEvent.InputTuple, DepositLimitUpdatedEvent.OutputTuple, DepositLimitUpdatedEvent.OutputObject>;
getEvent(key: 'FeeTransferred'): TypedContractEvent<FeeTransferredEvent.InputTuple, FeeTransferredEvent.OutputTuple, FeeTransferredEvent.OutputObject>;
getEvent(key: 'MinDepositUpdated'): TypedContractEvent<MinDepositUpdatedEvent.InputTuple, MinDepositUpdatedEvent.OutputTuple, MinDepositUpdatedEvent.OutputObject>;
getEvent(key: 'OperatorAdded'): TypedContractEvent<OperatorAddedEvent.InputTuple, OperatorAddedEvent.OutputTuple, OperatorAddedEvent.OutputObject>;
getEvent(key: 'OperatorRemoved'): TypedContractEvent<OperatorRemovedEvent.InputTuple, OperatorRemovedEvent.OutputTuple, OperatorRemovedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'StrategyAdded'): TypedContractEvent<StrategyAddedEvent.InputTuple, StrategyAddedEvent.OutputTuple, StrategyAddedEvent.OutputObject>;
getEvent(key: 'StrategyAllocationUpdated'): TypedContractEvent<StrategyAllocationUpdatedEvent.InputTuple, StrategyAllocationUpdatedEvent.OutputTuple, StrategyAllocationUpdatedEvent.OutputObject>;
getEvent(key: 'StrategyRemoved'): TypedContractEvent<StrategyRemovedEvent.InputTuple, StrategyRemovedEvent.OutputTuple, StrategyRemovedEvent.OutputObject>;
getEvent(key: 'StrategyReported'): TypedContractEvent<StrategyReportedEvent.InputTuple, StrategyReportedEvent.OutputTuple, StrategyReportedEvent.OutputObject>;
getEvent(key: 'StrategyStatusUpdated'): TypedContractEvent<StrategyStatusUpdatedEvent.InputTuple, StrategyStatusUpdatedEvent.OutputTuple, StrategyStatusUpdatedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
getEvent(key: 'WithdrawnFromStrategy'): TypedContractEvent<WithdrawnFromStrategyEvent.InputTuple, WithdrawnFromStrategyEvent.OutputTuple, WithdrawnFromStrategyEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'BufferTargetUpdated(uint256)': TypedContractEvent<BufferTargetUpdatedEvent.InputTuple, BufferTargetUpdatedEvent.OutputTuple, BufferTargetUpdatedEvent.OutputObject>;
      BufferTargetUpdated: TypedContractEvent<BufferTargetUpdatedEvent.InputTuple, BufferTargetUpdatedEvent.OutputTuple, BufferTargetUpdatedEvent.OutputObject>;
    

      'DeployedToStrategy(address,uint256)': TypedContractEvent<DeployedToStrategyEvent.InputTuple, DeployedToStrategyEvent.OutputTuple, DeployedToStrategyEvent.OutputObject>;
      DeployedToStrategy: TypedContractEvent<DeployedToStrategyEvent.InputTuple, DeployedToStrategyEvent.OutputTuple, DeployedToStrategyEvent.OutputObject>;
    

      'Deposit(address,address,uint256,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'DepositLimitUpdated(uint256)': TypedContractEvent<DepositLimitUpdatedEvent.InputTuple, DepositLimitUpdatedEvent.OutputTuple, DepositLimitUpdatedEvent.OutputObject>;
      DepositLimitUpdated: TypedContractEvent<DepositLimitUpdatedEvent.InputTuple, DepositLimitUpdatedEvent.OutputTuple, DepositLimitUpdatedEvent.OutputObject>;
    

      'FeeTransferred(string,uint256,address)': TypedContractEvent<FeeTransferredEvent.InputTuple, FeeTransferredEvent.OutputTuple, FeeTransferredEvent.OutputObject>;
      FeeTransferred: TypedContractEvent<FeeTransferredEvent.InputTuple, FeeTransferredEvent.OutputTuple, FeeTransferredEvent.OutputObject>;
    

      'MinDepositUpdated(uint256)': TypedContractEvent<MinDepositUpdatedEvent.InputTuple, MinDepositUpdatedEvent.OutputTuple, MinDepositUpdatedEvent.OutputObject>;
      MinDepositUpdated: TypedContractEvent<MinDepositUpdatedEvent.InputTuple, MinDepositUpdatedEvent.OutputTuple, MinDepositUpdatedEvent.OutputObject>;
    

      'OperatorAdded(address)': TypedContractEvent<OperatorAddedEvent.InputTuple, OperatorAddedEvent.OutputTuple, OperatorAddedEvent.OutputObject>;
      OperatorAdded: TypedContractEvent<OperatorAddedEvent.InputTuple, OperatorAddedEvent.OutputTuple, OperatorAddedEvent.OutputObject>;
    

      'OperatorRemoved(address)': TypedContractEvent<OperatorRemovedEvent.InputTuple, OperatorRemovedEvent.OutputTuple, OperatorRemovedEvent.OutputObject>;
      OperatorRemoved: TypedContractEvent<OperatorRemovedEvent.InputTuple, OperatorRemovedEvent.OutputTuple, OperatorRemovedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'StrategyAdded(address,uint256)': TypedContractEvent<StrategyAddedEvent.InputTuple, StrategyAddedEvent.OutputTuple, StrategyAddedEvent.OutputObject>;
      StrategyAdded: TypedContractEvent<StrategyAddedEvent.InputTuple, StrategyAddedEvent.OutputTuple, StrategyAddedEvent.OutputObject>;
    

      'StrategyAllocationUpdated(address,uint256)': TypedContractEvent<StrategyAllocationUpdatedEvent.InputTuple, StrategyAllocationUpdatedEvent.OutputTuple, StrategyAllocationUpdatedEvent.OutputObject>;
      StrategyAllocationUpdated: TypedContractEvent<StrategyAllocationUpdatedEvent.InputTuple, StrategyAllocationUpdatedEvent.OutputTuple, StrategyAllocationUpdatedEvent.OutputObject>;
    

      'StrategyRemoved(address)': TypedContractEvent<StrategyRemovedEvent.InputTuple, StrategyRemovedEvent.OutputTuple, StrategyRemovedEvent.OutputObject>;
      StrategyRemoved: TypedContractEvent<StrategyRemovedEvent.InputTuple, StrategyRemovedEvent.OutputTuple, StrategyRemovedEvent.OutputObject>;
    

      'StrategyReported(address,uint256,uint256,uint256)': TypedContractEvent<StrategyReportedEvent.InputTuple, StrategyReportedEvent.OutputTuple, StrategyReportedEvent.OutputObject>;
      StrategyReported: TypedContractEvent<StrategyReportedEvent.InputTuple, StrategyReportedEvent.OutputTuple, StrategyReportedEvent.OutputObject>;
    

      'StrategyStatusUpdated(address,uint8)': TypedContractEvent<StrategyStatusUpdatedEvent.InputTuple, StrategyStatusUpdatedEvent.OutputTuple, StrategyStatusUpdatedEvent.OutputObject>;
      StrategyStatusUpdated: TypedContractEvent<StrategyStatusUpdatedEvent.InputTuple, StrategyStatusUpdatedEvent.OutputTuple, StrategyStatusUpdatedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'Withdraw(address,address,address,uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    

      'WithdrawnFromStrategy(address,uint256,uint256)': TypedContractEvent<WithdrawnFromStrategyEvent.InputTuple, WithdrawnFromStrategyEvent.OutputTuple, WithdrawnFromStrategyEvent.OutputObject>;
      WithdrawnFromStrategy: TypedContractEvent<WithdrawnFromStrategyEvent.InputTuple, WithdrawnFromStrategyEvent.OutputTuple, WithdrawnFromStrategyEvent.OutputObject>;
    
    };
  }