/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace INonfungiblePositionManager {
      
    export type CollectParamsStruct = {tokenId: BigNumberish, recipient: AddressLike, amount0Max: BigNumberish, amount1Max: BigNumberish}

    export type CollectParamsStructOutput = [tokenId: bigint, recipient: string, amount0Max: bigint, amount1Max: bigint] & {tokenId: bigint, recipient: string, amount0Max: bigint, amount1Max: bigint }
  

    export type DecreaseLiquidityParamsStruct = {tokenId: BigNumberish, liquidity: BigNumberish, amount0Min: BigNumberish, amount1Min: BigNumberish, deadline: BigNumberish}

    export type DecreaseLiquidityParamsStructOutput = [tokenId: bigint, liquidity: bigint, amount0Min: bigint, amount1Min: bigint, deadline: bigint] & {tokenId: bigint, liquidity: bigint, amount0Min: bigint, amount1Min: bigint, deadline: bigint }
  

    export type IncreaseLiquidityParamsStruct = {tokenId: BigNumberish, amount0Desired: BigNumberish, amount1Desired: BigNumberish, amount0Min: BigNumberish, amount1Min: BigNumberish, deadline: BigNumberish}

    export type IncreaseLiquidityParamsStructOutput = [tokenId: bigint, amount0Desired: bigint, amount1Desired: bigint, amount0Min: bigint, amount1Min: bigint, deadline: bigint] & {tokenId: bigint, amount0Desired: bigint, amount1Desired: bigint, amount0Min: bigint, amount1Min: bigint, deadline: bigint }
  

    export type MintParamsStruct = {token0: AddressLike, token1: AddressLike, fee: BigNumberish, tickLower: BigNumberish, tickUpper: BigNumberish, amount0Desired: BigNumberish, amount1Desired: BigNumberish, amount0Min: BigNumberish, amount1Min: BigNumberish, recipient: AddressLike, deadline: BigNumberish}

    export type MintParamsStructOutput = [token0: string, token1: string, fee: bigint, tickLower: bigint, tickUpper: bigint, amount0Desired: bigint, amount1Desired: bigint, amount0Min: bigint, amount1Min: bigint, recipient: string, deadline: bigint] & {token0: string, token1: string, fee: bigint, tickLower: bigint, tickUpper: bigint, amount0Desired: bigint, amount1Desired: bigint, amount0Min: bigint, amount1Min: bigint, recipient: string, deadline: bigint }
  
    }

  export interface INonfungiblePositionManagerInterface extends Interface {
    getFunction(nameOrSignature: "approve" | "burn" | "collect" | "createAndInitializePoolIfNecessary" | "decreaseLiquidity" | "increaseLiquidity" | "mint" | "ownerOf" | "positions" | "transferFrom"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'burn', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'collect', values: [INonfungiblePositionManager.CollectParamsStruct]): string;
encodeFunctionData(functionFragment: 'createAndInitializePoolIfNecessary', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'decreaseLiquidity', values: [INonfungiblePositionManager.DecreaseLiquidityParamsStruct]): string;
encodeFunctionData(functionFragment: 'increaseLiquidity', values: [INonfungiblePositionManager.IncreaseLiquidityParamsStruct]): string;
encodeFunctionData(functionFragment: 'mint', values: [INonfungiblePositionManager.MintParamsStruct]): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'positions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collect', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAndInitializePoolIfNecessary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decreaseLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increaseLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'positions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
  }

  

  export interface INonfungiblePositionManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): INonfungiblePositionManager;
    waitForDeployment(): Promise<this>;

    interface: INonfungiblePositionManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    burn: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    collect: TypedContractMethod<
      [params: INonfungiblePositionManager.CollectParamsStruct, ],
      [[bigint, bigint] & {amount0: bigint, amount1: bigint }],
      'payable'
    >
    

    
    createAndInitializePoolIfNecessary: TypedContractMethod<
      [token0: AddressLike, token1: AddressLike, fee: BigNumberish, sqrtPriceX96: BigNumberish, ],
      [string],
      'payable'
    >
    

    
    decreaseLiquidity: TypedContractMethod<
      [params: INonfungiblePositionManager.DecreaseLiquidityParamsStruct, ],
      [[bigint, bigint] & {amount0: bigint, amount1: bigint }],
      'payable'
    >
    

    
    increaseLiquidity: TypedContractMethod<
      [params: INonfungiblePositionManager.IncreaseLiquidityParamsStruct, ],
      [[bigint, bigint, bigint] & {liquidity: bigint, amount0: bigint, amount1: bigint }],
      'payable'
    >
    

    
    mint: TypedContractMethod<
      [params: INonfungiblePositionManager.MintParamsStruct, ],
      [[bigint, bigint, bigint, bigint] & {tokenId: bigint, liquidity: bigint, amount0: bigint, amount1: bigint }],
      'payable'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    positions: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {nonce: bigint, operator: string, token0: string, token1: string, fee: bigint, tickLower: bigint, tickUpper: bigint, liquidity: bigint, feeGrowthInside0LastX128: bigint, feeGrowthInside1LastX128: bigint, tokensOwed0: bigint, tokensOwed1: bigint }],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'collect'): TypedContractMethod<
      [params: INonfungiblePositionManager.CollectParamsStruct, ],
      [[bigint, bigint] & {amount0: bigint, amount1: bigint }],
      'payable'
    >;
getFunction(nameOrSignature: 'createAndInitializePoolIfNecessary'): TypedContractMethod<
      [token0: AddressLike, token1: AddressLike, fee: BigNumberish, sqrtPriceX96: BigNumberish, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'decreaseLiquidity'): TypedContractMethod<
      [params: INonfungiblePositionManager.DecreaseLiquidityParamsStruct, ],
      [[bigint, bigint] & {amount0: bigint, amount1: bigint }],
      'payable'
    >;
getFunction(nameOrSignature: 'increaseLiquidity'): TypedContractMethod<
      [params: INonfungiblePositionManager.IncreaseLiquidityParamsStruct, ],
      [[bigint, bigint, bigint] & {liquidity: bigint, amount0: bigint, amount1: bigint }],
      'payable'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [params: INonfungiblePositionManager.MintParamsStruct, ],
      [[bigint, bigint, bigint, bigint] & {tokenId: bigint, liquidity: bigint, amount0: bigint, amount1: bigint }],
      'payable'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'positions'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {nonce: bigint, operator: string, token0: string, token1: string, fee: bigint, tickLower: bigint, tickUpper: bigint, liquidity: bigint, feeGrowthInside0LastX128: bigint, feeGrowthInside1LastX128: bigint, tokensOwed0: bigint, tokensOwed1: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }