/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IStrategyInterface extends Interface {
    getFunction(nameOrSignature: "asset" | "deploy" | "isActive" | "name" | "report" | "totalAssets" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DeployedToStrategy" | "StrategyReport" | "WithdrawnFromStrategy"): EventFragment;

    encodeFunctionData(functionFragment: 'asset', values?: undefined): string;
encodeFunctionData(functionFragment: 'deploy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'report', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'asset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deploy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'report', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DeployedToStrategyEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StrategyReportEvent {
      export type InputTuple = [profit: BigNumberish, loss: BigNumberish, totalAssets: BigNumberish];
      export type OutputTuple = [profit: bigint, loss: bigint, totalAssets: bigint];
      export interface OutputObject {profit: bigint, loss: bigint, totalAssets: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnFromStrategyEvent {
      export type InputTuple = [amount: BigNumberish, actualAmount: BigNumberish];
      export type OutputTuple = [amount: bigint, actualAmount: bigint];
      export interface OutputObject {amount: bigint, actualAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IStrategy extends BaseContract {
    
    connect(runner?: ContractRunner | null): IStrategy;
    waitForDeployment(): Promise<this>;

    interface: IStrategyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    asset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    deploy: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    isActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    report: TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {profit: bigint, loss: bigint, totalAssets: bigint }],
      'nonpayable'
    >
    

    
    totalAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [amount: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'asset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deploy'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'report'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint] & {profit: bigint, loss: bigint, totalAssets: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [amount: BigNumberish, receiver: AddressLike, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'DeployedToStrategy'): TypedContractEvent<DeployedToStrategyEvent.InputTuple, DeployedToStrategyEvent.OutputTuple, DeployedToStrategyEvent.OutputObject>;
getEvent(key: 'StrategyReport'): TypedContractEvent<StrategyReportEvent.InputTuple, StrategyReportEvent.OutputTuple, StrategyReportEvent.OutputObject>;
getEvent(key: 'WithdrawnFromStrategy'): TypedContractEvent<WithdrawnFromStrategyEvent.InputTuple, WithdrawnFromStrategyEvent.OutputTuple, WithdrawnFromStrategyEvent.OutputObject>;

    filters: {
      
      'DeployedToStrategy(uint256)': TypedContractEvent<DeployedToStrategyEvent.InputTuple, DeployedToStrategyEvent.OutputTuple, DeployedToStrategyEvent.OutputObject>;
      DeployedToStrategy: TypedContractEvent<DeployedToStrategyEvent.InputTuple, DeployedToStrategyEvent.OutputTuple, DeployedToStrategyEvent.OutputObject>;
    

      'StrategyReport(uint256,uint256,uint256)': TypedContractEvent<StrategyReportEvent.InputTuple, StrategyReportEvent.OutputTuple, StrategyReportEvent.OutputObject>;
      StrategyReport: TypedContractEvent<StrategyReportEvent.InputTuple, StrategyReportEvent.OutputTuple, StrategyReportEvent.OutputObject>;
    

      'WithdrawnFromStrategy(uint256,uint256)': TypedContractEvent<WithdrawnFromStrategyEvent.InputTuple, WithdrawnFromStrategyEvent.OutputTuple, WithdrawnFromStrategyEvent.OutputObject>;
      WithdrawnFromStrategy: TypedContractEvent<WithdrawnFromStrategyEvent.InputTuple, WithdrawnFromStrategyEvent.OutputTuple, WithdrawnFromStrategyEvent.OutputObject>;
    
    };
  }