/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IStakingBoost, IStakingBoostInterface } from "../../ShXRPVault.sol/IStakingBoost.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getBoost",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IStakingBoost__factory {
    static readonly abi = _abi;
    static createInterface(): IStakingBoostInterface {
      return new Interface(_abi) as IStakingBoostInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IStakingBoost {
      return new Contract(address, _abi, runner) as unknown as IStakingBoost;
    }
  }
  